### ISSUE TITLE
Can't parse status-json.xsl when only one source is available

### ISSUE THREAD

**Issue by mikelolasagasti** [markuslindenberg/icecast_exporter#1]
If only one is available icecast_exporter fails with the following output, as `status-json.xsl` returns an object instead of an array of  objects.

`time="2018-07-28T12:47:10Z" level=error msg="Can't read JSON: json: cannot unmarshal object into Go struct field .source of type []struct { Listeners int \"json:\\\"listeners\\\"\"; Listenurl string \"json:\\\"listenurl\\\"\"; ServerType string \"json:\\\"server_type\\\"\"; StreamStart main.ISO8601 \"json:\\\"stream_start_iso8601\\\"\" }" source="icecast_exporter.go:189"`

The problem is described at https://github.com/xiph/Icecast-Server/issues/12

**Comment by tweibert** [comment]
#3 should fix this

**Comment by markuslindenberg** [comment]
Merged, thanks.
